gasparin/gasparin/urls.py
from django.contrib import admin
from django.urls import include, path
from register.auth_logic import login_view  
from register.register_logic import register_view  
from menu.views import menu_view



urlpatterns = [
    path('video_processing/', include('video_processing.urls')),
    path('video_processing/', include('menu.urls')),
    path('', include('register.urls')),
    path('admin/', admin.site.urls),
]

gasparin/menu/urls.py
# urls.py

from django.contrib import admin
from django.urls import path
from .views import menu_view
from video_processing.views import index



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', menu_view, name='menu'),  
    path('', index, name='stream'),  
]

gasparin/register/urls.py
# urls.py

from django.contrib import admin
from django.urls import path
from .auth_logic import login_view
from .register_logic import register_view
from menu.views import menu_view



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', login_view, name='login'),
    path('register/', register_view, name='register'),  
    path('menu/', menu_view, name='menu'),  

]

gasparin/video_processing/urls.py
from django.urls import path

from . import views

app_name = 'video_processing'
urlpatterns = [
    path("", views.index, name="index"),
    path("video_feed", views.video_feed, name="video_feed"),
    path("live_video_feed", views.live_video_feed, name="live_video_feed"),
    path("legend_feed", views.legend_feed, name="legend_feed"),
    path("legend_live", views.legend_live, name="legend_live"),
]
 

gasparin/menu/models.py
from django.db import models

# Create your models here.

gasparin/register/models.py
from django.db import models

# Create your models here.

gasparin/video_processing/models.py
from django.db import models

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete = models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

gasparin/menu/views.py
# menu
import os
import json
from django.http import HttpResponse
from django.shortcuts import render, redirect
from gasparin.settings import BASE_DIR

JSON_FILE_PATH = os.path.join(BASE_DIR, 'video_processing', 'yolomodels', 'config.json')

def get_menu_options():
    if os.path.exists(JSON_FILE_PATH):
        with open(JSON_FILE_PATH, 'r') as file:
            return json.load(file)
    return {"task": "", "model": "", "visual": ""}

def save_menu_options(data):
    with open(JSON_FILE_PATH, 'w') as file:
        json.dump(data, file)

def menu_view(request):
    if request.method == 'POST':
        task = request.POST.get('task', '')
        model = request.POST.get('model', '')
        visual = request.POST.get('visual', '')

        # Load current menu options from JSON file
        menu_options = get_menu_options()

        # Update menu options
        if task:
            menu_options['task'] = task
        if model:
            menu_options['model'] = model
        if visual:
            menu_options['visual'] = visual
        
        save_menu_options(menu_options)

        return redirect('stream')

    elif request.method == 'GET':
        # Renderizar el formulario de registro con GET
        return render(request, 'menu.html')

gasparin/register/views.py
from django.shortcuts import render

# Create your views here.

gasparin/video_processing/views.py
from django.shortcuts import render
from django.http import StreamingHttpResponse, HttpResponse
from video_processing.camera import VideoCamera, Live_from_Video
from gasparin.settings import BASE_DIR

import os
import json

JSON_FILE_PATH = os.path.join(BASE_DIR, 'video_processing', 'yolomodels', 'config.json')

def get_menu_options():
    if os.path.exists(JSON_FILE_PATH):
        with open(JSON_FILE_PATH, 'r') as file:
            return json.load(file)
    return {"task": "", "model": "", "visual": ""}

# Create your views here.
def index(request):
	menu_options = get_menu_options()
	return render(request, 'video_processing/index.html',  {'menu_options': menu_options})

def gen(camera):
	while True:
		frame, legend = camera.get_frame()
		yield (b'--frame\r\n'
					b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')	

def legend_gen(camera):
	while True:
		frame, legend = camera.get_frame()
		yield (b'--frame\r\n'
		 			b'Content-Type: image/jpeg\r\n\r\n' + legend + b'\r\n\r\n')
		
def live_video_feed(request):
	return StreamingHttpResponse(gen(Live_from_Video()),
					content_type='multipart/x-mixed-replace; boundary=frame')

def video_feed(request):
	return StreamingHttpResponse(gen(VideoCamera()),
					content_type='multipart/x-mixed-replace; boundary=frame')

def legend_feed(request):
	return StreamingHttpResponse(legend_gen(VideoCamera()),
					content_type='multipart/x-mixed-replace; boundary=frame')

def legend_live(request):
	return StreamingHttpResponse(legend_gen(Live_from_Video()),
					content_type='multipart/x-mixed-replace; boundary=frame')

gasparin/menu/templates/menu.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Menú</title>
    <style>
        /* CSS */
        body {
            font-family: Arial, sans-serif;
            background-color: #f2f2f2;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }

        .container {
            width: 300px;
            padding: 20px;
            background-color: #ffffff;
            border-radius: 8px;
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        h2 {
            color: #333333;
            text-align: center;
        }

        .options {
            margin-bottom: 20px;
            display: flex;
            flex-direction: column;
            align-items: center;
        }

        .option {
            padding: 10px; /* Ajuste del tamaño del padding */
            margin: 5px;
            border: none;
            border-radius: 5px;
            background-color: #007bff;
            color: #ffffff;
            font-size: 16px;
            cursor: pointer;
        }

        .option:hover {
            background-color: #0056b3;
        }

        #modelSelection {
            margin-top: 20px;
        }

        .hidden {
            display: none;
        }

        label {
            display: block;
            margin-bottom: 5px;
            color: #333333;
            text-align: left;
        }

        select {
            width: 100%;
            padding: 10px;
            margin-bottom: 15px;
            border: 1px solid #cccccc;
            border-radius: 5px;
            box-sizing: border-box;
        }

        .buttons {
            display: flex;
            justify-content: space-between;
        }

        button {
            padding: 10px; /* Ajuste del tamaño del padding */
            border: none;
            border-radius: 5px;
            background-color: #007bff;
            color: #ffffff;
            font-size: 16px;
            cursor: pointer;
            transition: background-color 0.3s ease;
        }

        button:hover {
            background-color: #0056b3;
        }

        /* Espacio entre los botones */
        .buttons button + button {
            margin-left: 10px;
        }
    </style>

</head> 
<body>
    <div class="container">
        <h2>Menú</h2>
        <div class="options">
            <form id="mainForm" method="post">
                {% csrf_token %}
                <input type="hidden" id="taskInput" name="task" value="">
                <input type="hidden" id="modelInput" name="model" value="">
                <input type="hidden" id="visualInput" name="visual" value="">
                <button type="button" class="option" onclick="setTaskAndShowModels('ICSI')">ICSI</button>
                <button type="button" class="option" onclick="setTaskAndShowModels('Seleccionar esperma')">Seleccionar esperma</button>
                <button type="button" class="option" onclick="setTaskAndShowModels('Inmovilizar esperma')">Inmovilizar esperma</button>
            </form>
        </div>
        <div id="modelSelection" class="hidden">
            <label for="model">Seleccionar modelo:</label>
            <select id="model" onchange="setModel()">
                <option value="">--Seleccione un modelo--</option>
                <option value="YoloV5">YoloV5</option>
                <option value="YoloV8">YoloV8</option>
                <option value="YoloV9">YoloV9</option>
            </select>
            <div class="buttons">
                <button type="button" onclick="submitFormWithVisual('Live_video')">Conectar cámara</button>
                <button type="button" onclick="submitFormWithVisual('Video')">Subir video</button>
            </div>
        </div>
    </div>

    <script>
        function setTaskAndShowModels(task) {
            document.getElementById('taskInput').value = task;
            document.getElementById('modelSelection').classList.remove('hidden');
        }

        function setModel() {
            var model = document.getElementById('model').value;
            document.getElementById('modelInput').value = model;
        }

        function submitFormWithVisual(visual) {
            document.getElementById('visualInput').value = visual;
            document.getElementById('mainForm').submit();
        }
    </script>
</body>
</html>

gasparin/register/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Iniciar sesión</title>
    <link rel="stylesheet" type="text/css" href="{% static 'login.css' %}">
</head>
<body>
    <div class="container">
        <h2>Iniciar sesión</h2>
        
        {% if registration_message %}
        <p>{{ registration_message }}</p>
        {% endif %}
        
        <form method="post">
            {% csrf_token %}
            <label for="username">Nombre de usuario:</label><br>
            <input type="text" id="username" name="username"><br>
            <label for="password">Contraseña:</label><br>
            <input type="password" id="password" name="password"><br><br>
            <input type="submit" value="Iniciar sesión">
        </form>
        <p>¿No tienes una cuenta? <a href="{% url 'register' %}">Regístrate aquí</a>.</p>
    </div>
</body>
</html>

<style>
body {
    font-family: Arial, sans-serif;
    background-color: #f2f2f2;
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
    margin: 0;
}

.container {
    width: 300px;
    padding: 20px;
    background-color: #ffffff;
    border-radius: 8px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    display: flex;
    flex-direction: column;
    align-items: center;
}

h2 {
    color: #333333;
    text-align: center; /* Añadido para centrar el texto */
}

form {
    margin-top: 20px;
    width: 100%; /* Asegurar que el formulario ocupe todo el ancho */
}

label {
    display: block;
    margin-bottom: 5px;
    color: #333333;
    text-align: left;
}

input[type="text"],
input[type="password"],
input[type="submit"] {
    width: 100%;
    padding: 10px;
    margin-bottom: 15px;
    border: 1px solid #cccccc;
    border-radius: 5px;
    box-sizing: border-box;
}

input[type="submit"] {
    background-color: #007bff;
    border: none;
    color: #ffffff;
    font-size: 16px;
    cursor: pointer;
    transition: background-color 0.3s ease;
}

input[type="submit"]:hover {
    background-color: #0056b3;
}
</style>

gasparin/register/templates/register.html
<!-- register.html -->

{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Registrarse</title>
    <link rel="stylesheet" type="text/css" href="{% static 'register.css' %}">
</head>
<body>
    <div class="container">
        <h2>Registrarse</h2>
        
        <form method="post">
            {% csrf_token %}
            <label for="username">Nombre de usuario:</label><br>
            <input type="text" id="username" name="username"><br>
            <label for="password">Contraseña:</label><br>
            <input type="password" id="password" name="password"><br><br>
            <input type="submit" value="Registrarse">
        </form>
    </div>
</body>
</html>

<style>

/* register.css */

body {
    font-family: Arial, sans-serif;
    background-color: #f2f2f2;
    display: flex;
    justify-content: center;
    align-items: center;
    height: 100vh;
    margin: 0;
}

.container {
    width: 300px;
    padding: 20px;
    background-color: #ffffff;
    border-radius: 8px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    display: flex;
    flex-direction: column;
    align-items: center;
}

h2 {
    color: #333333;
    text-align: center; /* Añadido para centrar el texto */
}

form {
    margin-top: 20px;
    width: 100%; /* Asegurar que el formulario ocupe todo el ancho */
}

label {
    display: block;
    margin-bottom: 5px;
    color: #333333;
    text-align: left;
}

input[type="text"],
input[type="password"],
input[type="submit"] {
    width: 100%;
    padding: 10px;
    margin-bottom: 15px;
    border: 1px solid #cccccc;
    border-radius: 5px;
    box-sizing: border-box;
}

input[type="submit"] {
    background-color: #007bff;
    border: none;
    color: #ffffff;
    font-size: 16px;
    cursor: pointer;
    transition: background-color 0.3s ease;
}

input[type="submit"]:hover {
    background-color: #0056b3;
}


</style>

gasparin/video_processing/templates/video_processing/index.html
{% load static %}
<link rel="stylesheet" href="{% static 'style.css' %}" type="text/css" media="screen">

<head>
    <title>GASPARIN</title>
</head>
<body>
    <div class="header">
    <h1 >Video Live Detection</h1>
    </div>
    {% if  menu_options.visual == 'Video' %}
        <div class="video">
            <div class="stream">
                <img class = "live-leg" src = "{% url 'video_processing:legend_feed' %}">
            </div>
            <span></span><span></span>
            <div class="stream">    
                <img class = "live-vid" src = "{% url 'video_processing:video_feed' %}">
            </div>
        </div>
    {% else %}
    <div class="video">
        <div class="stream">
            <img class = "live-leg" src = "{% url 'video_processing:legend_live' %}">
        </div>
        <span></span><span></span>
        <div class="stream">    
            <img class = "live-vid" src = "{% url 'video_processing:live_video_feed' %}">
        </div>
    </div>
    {% endif %}
</body>